version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run: apt-get update && apt-get install -yy git ssh emacs
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: make compile
      - run: make test
