version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run: sudo apt-get update && sudo apt-get install -yy git ssh emacs-nox make
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: emacs --version
      - run: make
